### ISSUE TITLE
Misuse of public apis can result in private key exposure

### ISSUE THREAD

**Issue by cjimison** [potatosalad/erlang-libdecaf#13]
MystenLabs identified erlang-libdecaf as one potentially unsafe library.  Might be worth adding some docs, warning or exceptions in such a case.

https://github.com/MystenLabs/ed25519-unsafe-libs

**Comment by potatosalad** [comment]
@cjimison Awesome, thank you for reporting this!  This will be fixed in the next release.

**Comment by kchalkias** [comment]
Awesome work [potatosalad](https://github.com/potatosalad) re resolving this + error handling + logging!
