### ISSUE TITLE
failed on compile

### ISSUE THREAD

**Issue by mkaravaev** [potatosalad/erlang-libdecaf#3]
```
===> Compiling libdecaf
./build/obj/bin/decaf_gen_tables_curve25519 > src/GENERATED/c/curve25519/decaf_tables.c || (rm src/GENERATED/c/curve25519/decaf_tables.c; exit 1)
/bin/sh: line 1: 52292 Illegal instruction: 4  ./build/obj/bin/decaf_gen_tables_curve25519 > src/GENERATED/c/curve25519/decaf_tables.c
make[1]: *** [src/GENERATED/c/curve25519/decaf_tables.c] Error 1
make: *** [/Users/misa/Dropbox/Elixir/topo/deps/libdecaf/.ed448goldilocks/build/lib/libdecaf.so.1] Error 2
===> Hook for compile failed!
```

**Comment by potatosalad** [comment]
Would you mind sharing your compiler version `cc --version` and the specs for your machine?

It looks like an Apple computer, but knowing the model and year would be helpful. I suspect that the default `ARCHFLAGS` may not be compatible with your machine.

**Comment by mkaravaev** [comment]
@potatosalad 
Apple LLVM version 7.0.2 (clang-700.1.81)
Target: x86_64-apple-darwin14.5.0
Thread model: posix

MacBook Pro (13-inch, Mid 2012)
OS X Yosmite 10.10.5 (14F1909)

**Comment by potatosalad** [comment]
@mkaravaev You might need to update your compiler or adjust your `ARCHFLAGS`.

Apple LLVM version 7.0.2 is equivalent to Clang version 3.7 (I think...for some reason Apple uses different version numbers, so it's hard to tell).  Clang version 3.8 is known to work on OS X 10.11.x (so Apple LLVM version 7.3.0 (clang-703.0.31)).

Alternatively, you can try prefixing `ARCHFLAGS=-Wgcc-compat` to your compile command to disable some of the extra CPU features not supported by your machine or compiler.
